(use judge)
(use ../src/gurp)
(use ../src/command-lib)

(deftest list-doers
  (test
    (strip-ansi (list-doers))
    @"                       apk  Install and uninstall APK packages. Only\n                            valid in an Alpine LX zone.\n                    bridge  Create and modify ethernet bridges.\n                      cron  Manage cron jobs. Crontab entries are\n                            prefixed with a machine-generated string.\n                 directory  Create and remove directories. Parents are\n                            created like mkdir -p, but with the\n                            owner/group/mode of the gurp process. Removal\n                            always removes directory contents.\n                 etherstub  Create and destroy etherstubs.\n                 file-line  Ensure lines do or do not exist in the\n                            given file.\n                      file  Create files from multiple sources, or\n                            remove them.\n                       gem  Install and uninstall Ruby gems.\n                     group  Create and destroy Unix groups.\n                ip-address  Manages IP addresses via ipadm.\n              ip-interface  Create and destroy IP interfaces, with\n                            optional properties. Properties are supplied with\n                            'ip-interface-protocol'.\n             ip-properties  Sets global IP properties, via 'ipadm\n                            set-prop'.\n                  ipfilter  Set or remove ipfilter rules.\n                     ipnat  Set or remove NAT rules.\n                      misc  A collection of things too small to deserve\n                            their own doer.\n              network-flow  Manage network flows via flowadm.\n                       pkg  Install and uninstall pkg(5) packages.\n                     pkgin  Install and uninstall pkgin packages. Only\n                            valid in a pkgsrc zone.\n                 publisher  Add and remove pkg(5) publisher origins.\n                     route  Manage routes. Note that default routes for\n                            zones should be handled by the zone's :defrouter\n                            property.\n                       smf  Create and install a manifest for an SMF\n                            service.\n                       svc  Manage the state of an existing SMF\n                            service.\n                   svcprop  Set and remove properties and property\n                            groups of an existing SMF service.\n                   symlink  Create and remove symbolic links.\n                      user  Manage Unix users\n                      vlan  Manage VLAN objects\n                      vnic  Manage VNIC objects\n                       zfs  Create, destroy, and modify properties of\n                            ZFS filesystems.\n                      zone  Create and destroy zones. Existing zones\n                            cannot be modified."))

(deftest help-for-doer
  (test
    (strip-ansi (help-for "directory"))
    @"directory\n  Create and remove directories. Parents are created like mkdir -p, but with\n  the owner/group/mode of the gurp process. Removal always removes directory\n  contents.\n\ndirectory/ensure\n  name  [:string]  Fully qualified path to directory\n\nMandatory properties\n  owner [:string :number]  The username or UID of the user who owns\n                           this directory\n  group [:string :number]  The group name or GID of the for this\n                           directory\n  mode  [:string]          Permissions, written as a four-digit octal\n\nOptional properties\n  None\n\ndirectory/remove\n\nMandatory properties\n  None\n\nOptional properties\n  None\n\nNotes\n  Directories are created/removed in the order of a natural sort.\n\n  Directories are created 'mkdir -p' style, but only the mode and owner of the\n  specified directory are managed by Gurp. Any directories 'filled in' to get\n  to the target path will have their ownership and mode dictated by the Gurp\n  process and its umask.\n\n  Removing a directory removes all its contents, but does not remove any empty\n  ancestors.\n\n"))

(deftest help-for-helpers
  (test
    (strip-ansi (help-for "zone/network"))
    @"zone/network\n  Describe network configuration of a zone resource.\n\n  name  [:string]  Zone VNIC, which may already exist\n\nMandatory properties\n  physical [:string]  Zone VNIC. This is the name of the resource, and\n                      is not specified with a key\n\nOptional properties\n  global-nic      [:string]  Physical NIC on which to create zone VNIC\n  allowed-address [:string]  IP address, with /netmask\n  defrouter       [:string]  IP address of default router\n"))
