{
 "title": "Gurp Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gurp Managed Resources",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(gurp_resources, \"host\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Client Apply Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "gurp_ms_time", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Client Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "gurp_changes[20s]", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "gurp_error_ms_time[20s]", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "HTTP Request Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total)[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Config Request Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{path=~\"^/config.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Client Config Request TIme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_request_duration_seconds_sum{path=~\"^/config.*\"}[5m])) / \nsum by (path) (rate(http_request_duration_seconds_count{path=~\"^/config.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average File Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{path=~\"^/file.*\"}[5m])) / \nsum(rate(http_request_duration_seconds_count{path=~\"^/file.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Config Request TIme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{path=~\"^/config.*\"}[5m])) / \nsum(rate(http_request_duration_seconds_count{path=~\"^/config.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "http_requests_total{status=\"4xx\"}[5m]",
     "legendFormat": "__auto"
    },
    {},
    {}
   ]
  },
  {
   "title": "5xx Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "http_requests_total{status=\"5xx\"}[5m]",
     "legendFormat": "__auto"
    },
    {},
    {}
   ]
  }
 ]
}