[package]
name = "tester"
version = "2.1.0"
edition = "2024"

[dependencies]
camino = { version = "1.1.9", features = ["serde1"] }
common = { path = "../common" }
embed = {path = "../embed" }
janetrs = "0.8.0"
nix = { version = "0.31.0", features = ["user"] }
serde_json = "1.0.149"
serde = { version = "1", features = ["derive"] }
