[package]
name = "util"
version = "2.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
camino = { version = "1.1.9", features = ["serde1"] }
common = { path = "../common" }
macros = { path = "../macros" }
nix = { version = "0.31", features = ["fs", "hostname", "user"] }
opentelemetry = "0.32.0"
opentelemetry_sdk = { version = "0.32.0", features = ["rt-tokio", "metrics"]}
opentelemetry-otlp = { version = "0.32.0", features = ["metrics", "http-proto"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1.41"
ureq = "3.1.0"
xml-rs = "1.0.0"
xmlwriter = "0.1.0"
blake3 = "1.8.4"
regex = "1.12.3"
sha256 = "1.6.0"

[dev-dependencies]
indoc = "2.0.7"
pretty_assertions = "1.4.1"
tester = { path = "../tester" }

[build-dependencies]
vergen-git2 = { version = "9.1.0", features = ["build", "cargo", "rustc", "si"] }
