[package]
name = "util"
version = "1.4.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
camino = { version = "1.1.9", features = ["serde1"] }
common = { path = "../common" }
macros = { path = "../macros" }
nix = { version = "0.30.1", features = ["fs", "user"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1.41"
ureq = "3.1.0"
xmlwriter = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
tester = { path = "../tester" }
