name: Janet Tests
permissions:
  contents: read
on:
  - push
jobs:
  janet-tests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build Docker Image
        run: docker build -t janet-tests ./janet_src
      - name: Run Janet Tests
        run: docker run --rm janet-tests
