name: Janet Tests
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths:
      - janet/**
      - .github/workflows/janet-tests.yml
  pull_request:
    paths:
      - janet/**
      - .github/workflows/janet-tests.yml

concurrency:
  group: test-janet
  cancel-in-progress: true

jobs:
  janet-tests:
    name: Run Janet Tests
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          persist-credentials: false
      - name: Build Docker Image
        run: docker build -t janet-tests ./janet
      - name: Run Janet Tests
        run: docker run --rm janet-tests
