name: Janet Tests
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - janet/**
      - .github/workflows/janet-tests.yml
  pull_request:
    paths:
      - janet/**
      - .github/workflows/janet-tests.yml

jobs:
  janet-tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: Build Docker Image
        run: docker build -t janet-tests ./janet
      - name: Run Janet Tests
        run: docker run --rm janet-tests
