name: Rust Tests
permissions:
  contents: read
on: 
  - push
jobs:
  rust-tests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
    steps:
      - uses: hecrj/setup-rust-action@110f36749599534ca96628b82f52ae67e5d95a3c
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Audit Rust deps
        run: |
          cargo install cargo-audit --locked
          cargo audit 
      - name: Run Rust Tests
        run: cargo test -- --include-ignored
